name: .NET 9 Release Build

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      input:
        description: "Bond service"
        required: false
        default: "BondService"

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '9.0.x'

      - name: Restore Workload
        run: dotnet workload restore

      - name: Restore Packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Trust HTTPS certificate
        run: dotnet dev-certs https --trust

    #   - name: Run tests
    #     run: dotnet test --no-build --configuration Release --verbosity normal